addons:
  code_climate:
    repo_token:
      secure: "oAB9RdC2ie8n1dHS0ZGufSjAuTHOkPaxQIgZ5c59uTO0XWYxsMS8atw1DdibS/duSM0pzf/ByHpx0qGKUn2DJIE/fCtlVaddICOgH5i2v8q9Zbn0EFiEaTZxzdyhKoENIdcs5iKrOr2g+kntaaGTbl/f1+eKWON+nbTqc2tuqvOG21tG7q0Fwrx2zE8QUDJXucGaTzbC6eeCbQ0nJ4KVGkcJBU4Ce8y7kY6dNS30x77zdB1IKvw4vTUDQLgkWV91PfNDnME2ghM45me77JFaOWBSQ6JSbr1kbGrDf0Ega6GT04k+c06QeTX7EdBeBkpwExR2XYTpkAx6ZlbXErcrI3UynyjusbUWovBwcJDHCE7vZelF/+TsmRIpd0Gh0jiT4Rv51P9VU9k6LC+gbcPsPnJgd05sJmFrcDLh/lZt4g3Dc3TRFOVP6Y2Z8OSbmRSWaByM5QV7BVDcX37dwYWBcVlOhxcCIORnf2tlZ4zcKFUNbgbEAthfQAXBXsW2rsBnqf3DwmviwAgGBzmSozyCw0NbUxDKUG+9wPzyAyjqYOX00s2vqGkeb+q4SoDy40reyJk0xRIIZYDtrzBBF+BRLX0xh3FG3PcySFYzyWS6uk95nl0UUvK3E3z+RzLdlk05K6Gvz2ua2/YOW86LXOlJQkZEHvFCb0KTqHkmdIvyG7Y="
language: ruby
sudo: false
cache: bundler
before_install:
- gem install bundler
before_script:
- createdb pgconstraint-test
rvm:
- 2.4.0
- 2.3.0
- 2.2.2
notifications:
  email: false
gemfile:
- gemfiles/activerecord_4.2.8.gemfile
- gemfiles/activerecord_5.0.3.gemfile
- gemfiles/activerecord_5.1.1.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
